### ISSUE TITLE
[Question] How could I update record with valid_from and valid_to fields

### ISSUE THREAD

**Issue by linhdangduy** [kufu/activerecord-bitemporal#71]
First of all, thank you for great gem!

## Problem
I have tried the gem but stuck with the idea below:

Given: at present ("2019/1/10")
```ruby
Timecop.freeze("2019/1/10") {
  # create new employee
  employee = Employee.create(emp_code: "001", name: "Jane", valid_from: "2019/1/1")
}
```

Now, this employee has changed her name to Jenny from `2019/1/3`, so I want to update this employee's name to Jenny with valid_from: `2019/1/3`. How can I achieve it?

## Things I have tried

```ruby
Timecop.freeze("2019/1/10") {
  # create new employee
  employee = Employee.create(emp_code: "001", name: "Jane", valid_from: "2019/1/1")

  # update name and valid_from
  employee.update(name: "Jenny", valid_from: "2019/1/3")
}
```

But seem like `valid_from` did not change with this update command, it only created the new record with name: "Jenny" and valid_from is present datetime ("2019/1/10") which is wrong

Thank a lot!

**Comment by osyo-manga** [comment]
hi, You can try `#valid_at` :)

```ruby
Timecop.freeze("2019/1/10") {
  # create new employee
  employee = Employee.create(emp_code: "001", name: "Jane", valid_from: "2019/1/1")

  employee.valid_at("2019/1/3") { |record|
    record.update(name: "Jenny")
  }
  pp Employee.ignore_valid_datetime.order(:valid_from).pluck(:name, :valid_from, :valid_to)
  # => [["Jane", 2019-01-01 00:00:00 UTC, 2019-01-03 00:00:00 UTC],
  #     ["Jenny", 2019-01-03 00:00:00 UTC, 9999-12-31 00:00:00 UTC]]
}
```

**Comment by linhdangduy** [comment]
Awesome, I tried `#valid_at` and it works!
Thank you so much!

It is so helpful if `valid_at` has its docs at README. Seem current README has only class method `.valid_at` :D
