### ISSUE TITLE
When will the latest version be released?

### ISSUE THREAD

**Issue by endotakuya** [kufu/activerecord-bitemporal#89]
Hey there.

Thank you for this great library.

I would like to try it out, but the latest version of RubyGems seems to be still v0.0.1.
https://rubygems.org/gems/activerecord-bitemporal

Do you have plans to release ongoing commits?

**Comment by kinoppyd** [comment]
@endotakuya 

Hi!

Thank you for trying AR::Bitemporal gem, and sorry for we forget to push latest version  to RubyGems.
Now, we discussing about how release latest version and future release strategy.

We will release latest version soon, please give us some time.

**Comment by kinoppyd** [comment]
@endotakuya 

I’m sorry to have kept you waiting. Today we released 1.0.0 and you can use newest version via RubyGems.
This issue has helped us define our release strategy. We thank you.

**Comment by endotakuya** [comment]
@kinoppyd 

Thanks for the reply and release. I will try the new version right away!
